Logging is configured.
======================================================= test session starts ========================================================
platform win32 -- Python 3.12.4, pytest-8.3.2, pluggy-1.5.0
rootdir: C:\Users\150194\OneDrive - Arrow Electronics, Inc\Documents\Python\pytest-project
configfile: pytest.ini
plugins: allure-pytest-2.13.5, html-4.1.1, html-reporter-0.2.9, metadata-3.1.1
collected 11 items / 10 deselected / 1 selected

tests/api/test_api_todo_pixegami.py::test_api_get_task_by_invalid_id FAILED

============================================================= FAILURES =============================================================
_________________________________________________ test_api_get_task_by_invalid_id __________________________________________________

    def test_api_get_task_by_invalid_id():
        task_id = 1000
>       Logger.info('Get task by task id: '+task_id+" which is not present.")
E       TypeError: can only concatenate str (not "int") to str

tests\api\test_api_todo_pixegami.py:118: TypeError
===================================================== short test summary info ======================================================
FAILED tests/api/test_api_todo_pixegami.py::test_api_get_task_by_invalid_id - TypeError: can only concatenate str (not "int") to str
================================================= 1 failed, 10 deselected in 0.88s =================================================
