Logging is configured.
======================================================= test session starts ========================================================
platform win32 -- Python 3.12.4, pytest-8.3.2, pluggy-1.5.0
rootdir: C:\Users\150194\OneDrive - Arrow Electronics, Inc\Documents\Python\pytest-project
configfile: pytest.ini
plugins: html-4.1.1, metadata-3.1.1
collected 9 items

tests/api/test_api_todo_pixegami.py::test_api_get getting response message

---------------------------------------------------------- live log call -----------------------------------------------------------
2024-08-07 22:07:55 INFO getting response message
Starting new HTTPS connection (1): todo.pixegami.io:443
https://todo.pixegami.io:443 "GET / HTTP/11" 200 39
{'message': 'Hello World from Todo API'}
200
PASSED
tests/api/test_api_todo_pixegami.py::test_api_put_create_task Starting new HTTPS connection (1): todo.pixegami.io:443
https://todo.pixegami.io:443 "PUT /create-task HTTP/11" 200 187
{'task': {'user_id': 'Test User 1', 'content': 'My test content with json file.', 'is_done': False, 'created_time': 1723048677, 'task_id': 'task_aec399638731404a8a4b1436036b235a', 'ttl': 1723135077}}
task_aec399638731404a8a4b1436036b235a
Creating new task with id: task_aec399638731404a8a4b1436036b235a

---------------------------------------------------------- live log call -----------------------------------------------------------
2024-08-07 22:08:00 INFO Creating new task with id: task_aec399638731404a8a4b1436036b235a
200
PASSED
tests/api/test_api_todo_pixegami.py::test_api_put_create_task_invalid_data_type Starting new HTTPS connection (1): todo.pixegami.io:443
https://todo.pixegami.io:443 "PUT /create-task HTTP/11" 422 111
<Response [422]>
{'detail': [{'loc': ['body', 'is_done'], 'msg': 'value could not be parsed to a boolean', 'type': 'type_error.bool'}]}
Creating task with invalid data type.

---------------------------------------------------------- live log call -----------------------------------------------------------
2024-08-07 22:08:01 INFO Creating task with invalid data type.
value could not be parsed to a boolean
422
PASSED
tests/api/test_api_todo_pixegami.py::test_api_put_create_task_missing_required_field Starting new HTTPS connection (1): todo.pixegami.io:443
https://todo.pixegami.io:443 "PUT /create-task HTTP/11" 422 91
<Response [422]>
{'detail': [{'loc': ['body', 'content'], 'msg': 'field required', 'type': 'value_error.missing'}]}
Creating task with missing one of required field.

---------------------------------------------------------- live log call -----------------------------------------------------------
2024-08-07 22:08:02 INFO Creating task with missing one of required field.
field required
422
PASSED
tests/api/test_api_todo_pixegami.py::test_api_put_create_task_invalid_creationtime SKIPPED (unconditional skip)
tests/api/test_api_todo_pixegami.py::test_api_get_task_by_id task_aec399638731404a8a4b1436036b235a
Get task by task id: task_aec399638731404a8a4b1436036b235a

---------------------------------------------------------- live log call -----------------------------------------------------------
2024-08-07 22:08:02 INFO Get task by task id: task_aec399638731404a8a4b1436036b235a
Starting new HTTPS connection (1): todo.pixegami.io:443
https://todo.pixegami.io:443 "GET /get-task/task_aec399638731404a8a4b1436036b235a HTTP/11" 200 178
{'is_done': False, 'content': 'My test content with json file.', 'ttl': 1723135077, 'user_id': 'Test User 1', 'task_id': 'task_aec399638731404a8a4b1436036b235a', 'created_time': 1723048677}
200
PASSED
tests/api/test_api_todo_pixegami.py::test_api_get_task_by_user_id Get task by user id: Test User 1

---------------------------------------------------------- live log call -----------------------------------------------------------
2024-08-07 22:08:03 INFO Get task by user id: Test User 1
Starting new HTTPS connection (1): todo.pixegami.io:443
https://todo.pixegami.io:443 "GET /list-tasks/Test%20User%201 HTTP/11" 200 1040
{'tasks': [{'is_done': False, 'content': 'My test content with json file.', 'ttl': 1723135077, 'user_id': 'Test User 1', 'task_id': 'task_aec399638731404a8a4b1436036b235a', 'created_time': 1723048677}, {'is_done': False, 'content': 'My test content.', 'ttl': 1723120810, 'user_id': 'Test User 1', 'task_id': 'task_c937175d045e4564ae4e0eb2e33e28da', 'created_time': 1723034410}, {'is_done': False, 'content': 'My test content.', 'ttl': 1723117717, 'user_id': 'Test User 1', 'task_id': 'task_883165fcf2854406b47d17dcaf34ea55', 'created_time': 1723031317}, {'is_done': False, 'content': 'My test content with json file.', 'ttl': 1723117711, 'user_id': 'Test User 1', 'task_id': 'task_37bea58ba4764126bf703e9286961b3c', 'created_time': 1723031311}, {'is_done': False, 'content': 'My test content.', 'ttl': 1723117594, 'user_id': 'Test User 1', 'task_id': 'task_af356dfedc9a45b6bd47ce99055ae4fa', 'created_time': 1723031194}, {'is_done': False, 'content': 'My test content with json file.', 'ttl': 1723117589, 'user_id': 'Test User 1', 'task_id': 'task_c193cfca7e2c463ab74c0ccaba1a56db', 'created_time': 1723031189}]}
200
PASSED
tests/api/test_api_todo_pixegami.py::test_api_update_task Update task with id: task_aec399638731404a8a4b1436036b235a

---------------------------------------------------------- live log call -----------------------------------------------------------
2024-08-07 22:08:04 INFO Update task with id: task_aec399638731404a8a4b1436036b235a
FAILED
tests/api/test_api_todo_pixegami.py::test_api_del_task_by_id Delete task with id: task_aec399638731404a8a4b1436036b235a

---------------------------------------------------------- live log call -----------------------------------------------------------
2024-08-07 22:08:05 INFO Delete task with id: task_aec399638731404a8a4b1436036b235a
Starting new HTTPS connection (1): todo.pixegami.io:443
https://todo.pixegami.io:443 "DELETE /delete-task/task_aec399638731404a8a4b1436036b235a HTTP/11" 200 59
{'deleted_task_id': 'task_aec399638731404a8a4b1436036b235a'}
200
Validate task is deleted or not.
2024-08-07 22:08:06 INFO Validate task is deleted or not.
Starting new HTTPS connection (1): todo.pixegami.io:443
https://todo.pixegami.io:443 "GET /get-task/task_aec399638731404a8a4b1436036b235a HTTP/11" 404 65
{'detail': 'Task task_aec399638731404a8a4b1436036b235a not found'}
404
PASSED

============================================================= FAILURES =============================================================
_______________________________________________________ test_api_update_task _______________________________________________________

    def test_api_update_task():
    
        Logger.info("Update task with id: "+task_id)
>       response = HelperClass.update_task(json_payload["update_payload"])
E       KeyError: 'update_payload'

tests\api\test_api_todo_pixegami.py:130: KeyError
-------------------------------------------------------- Captured log call ---------------------------------------------------------
2024-08-07 22:08:04 INFO Update task with id: task_aec399638731404a8a4b1436036b235a
- Generated html report: file:///C:/Users/150194/OneDrive%20-%20Arrow%20Electronics%2C%20Inc/Documents/Python/pytest-project/reports/report.html -
===================================================== short test summary info ======================================================
FAILED tests/api/test_api_todo_pixegami.py::test_api_update_task - KeyError: 'update_payload'
============================================= 1 failed, 7 passed, 1 skipped in 13.14s ==============================================
