Logging is configured.
======================================================= test session starts ========================================================
platform win32 -- Python 3.12.4, pytest-8.3.2, pluggy-1.5.0
rootdir: C:\Users\150194\OneDrive - Arrow Electronics, Inc\Documents\Python\pytest-project
configfile: pytest.ini
plugins: html-4.1.1, metadata-3.1.1
collected 9 items / 8 deselected / 1 selected

tests/api/test_api_todo_pixegami.py::test_api_put_create_task_missing_required_field Starting new HTTPS connection (1): todo.pixegami.io:443
https://todo.pixegami.io:443 "PUT /create-task HTTP/11" 422 91
<Response [422]>
{'detail': [{'loc': ['body', 'content'], 'msg': 'field required', 'type': 'value_error.missing'}]}
Creating task with missing one of required field.

---------------------------------------------------------- live log call -----------------------------------------------------------
2024-08-07 17:53:30 INFO Creating task with missing one of required field.
field required
422
PASSED

- Generated html report: file:///C:/Users/150194/OneDrive%20-%20Arrow%20Electronics%2C%20Inc/Documents/Python/pytest-project/reports/report.html -
================================================= 1 passed, 8 deselected in 1.56s ==================================================
