Logging is configured.
======================================================= test session starts ========================================================
platform win32 -- Python 3.12.4, pytest-8.3.2, pluggy-1.5.0
rootdir: C:\Users\150194\OneDrive - Arrow Electronics, Inc\Documents\Python\pytest-project
configfile: pytest.ini
plugins: allure-pytest-2.13.5, html-4.1.1, html-reporter-0.2.9, metadata-3.1.1
collected 14 items / 13 deselected / 1 selected

tests/test_flow.py::test_api_task_flow Creating task.

---------------------------------------------------------- live log call -----------------------------------------------------------
2024-08-09 15:40:44 INFO Creating task.
Starting new HTTPS connection (1): todo.pixegami.io:443
https://todo.pixegami.io:443 "PUT /create-task HTTP/11" 200 200
{'task': {'user_id': 'Test User Jaymin', 'content': 'My test content with for Test User New.', 'is_done': False, 'created_time': 1723198244, 'task_id': 'task_7354974884014a9c8aa6033e958ce5fc', 'ttl': 1723284644}}
1.283512
200
Task created successfully.
2024-08-09 15:40:45 INFO Task created successfully.
Updating task.
2024-08-09 15:40:45 INFO Updating task.
Starting new HTTPS connection (1): todo.pixegami.io:443
https://todo.pixegami.io:443 "PUT /update-task HTTP/11" 200 59
{'updated_task_id': 'task_7354974884014a9c8aa6033e958ce5fc'}
1.12464
200
Get task with id: task_7354974884014a9c8aa6033e958ce5fc and validate if task is updated or not.
2024-08-09 15:40:46 INFO Get task with id: task_7354974884014a9c8aa6033e958ce5fc and validate if task is updated or not.
Starting new HTTPS connection (1): todo.pixegami.io:443
https://todo.pixegami.io:443 "GET /get-task/task_7354974884014a9c8aa6033e958ce5fc HTTP/11" 200 183
{'content': 'Updated content with json Jaymin', 'is_done': True, 'ttl': 1723284644, 'user_id': 'Test User Jaymin', 'task_id': 'task_7354974884014a9c8aa6033e958ce5fc', 'created_time': 1723198244}
1.123008
Task updated successfully.
2024-08-09 15:40:47 INFO Task updated successfully.
Deleting task.
2024-08-09 15:40:47 INFO Deleting task.
Starting new HTTPS connection (1): todo.pixegami.io:443
https://todo.pixegami.io:443 "DELETE /delete-task/task_7354974884014a9c8aa6033e958ce5fc HTTP/11" 200 59
{'deleted_task_id': 'task_7354974884014a9c8aa6033e958ce5fc'}
1.09337
200
Task deleted successfully.
2024-08-09 15:40:48 INFO Task deleted successfully.
Validating whether task is deleted or not.
2024-08-09 15:40:48 INFO Validating whether task is deleted or not.
Starting new HTTPS connection (1): todo.pixegami.io:443
https://todo.pixegami.io:443 "GET /get-task/task_7354974884014a9c8aa6033e958ce5fc HTTP/11" 404 65
{'detail': 'Task task_7354974884014a9c8aa6033e958ce5fc not found'}
0.857704
404
Task deleted and not found.
2024-08-09 15:40:49 INFO Task deleted and not found.
PASSED
C:\Users\150194\OneDrive - Arrow Electronics, Inc\Documents\Python\pytest-project\API_VENV\Lib\site-packages\_pytest\terminal.py:903: PluggyTeardownRaisedWarning: A plugin raised an exception during an old-style hookwrapper teardown.
Plugin: 1849445511248, Hook: pytest_terminal_summary
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\150194\\OneDrive - Arrow Electronics, Inc\\Documents\\Python\\pytest-project/output.json' -> 'C:\\Users\\150194\\OneDrive - Arrow Electronics, Inc\\Documents\\Python\\pytest-project/archive\\output_1723198244.005697.json'
For more information see https://pluggy.readthedocs.io/en/stable/api_reference.html#pluggy.PluggyTeardownRaisedWarning
  self.config.hook.pytest_terminal_summary(
